# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level_diff', models.IntegerField()),
                ('mobtype', models.IntegerField()),
                ('cr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('g', models.FloatField()),
                ('i', models.FloatField()),
                ('b', models.FloatField()),
                ('a', models.FloatField()),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='critcalculator.Class')),
            ],
        ),
    ]
