# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critcalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='base_cf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
